### ISSUE TITLE
Documentation push

### ISSUE THREAD

**Issue by timtiemens** [graphql-java-kickstart/documentation#3]
The source file at https://github.com/graphql-java-kickstart/documentation/blob/master/content/servlet/getting-started/index.md
has been updated to say "query { hello }" -- and that is correct.
However, the website document at https://www.graphql-java-kickstart.com/servlet/getting-started/
still says "query { test }"
The source needs pushed to the target.

**Comment by vojtapol** [comment]
The deployment of the documentation site has been fixed.
