### ISSUE TITLE
Link on main Graphql Kickstart page navigates to wrong page

### ISSUE THREAD

**Issue by Cat-Lord** [graphql-java-kickstart/documentation#35]
Link provided on [the main page](https://github.com/graphql-java-kickstart) just under the "GraphQL Java Kickstart" heading navigates to a [dummy wordpress page](https://graphql-java-kickstart.com/) instead of the [main page](https://www.graphql-java-kickstart.com/).
Caused by missing 'www' after the https protocol in the link. Tested in Mozilla Firefox 100.0 and Chrome 101.0.4951.64.

Edit: Added faulty and (expected) main page link.

**Comment by setchy** [comment]
Thanks for reporting @Cat-Lord.

@oliemansm - do you know if there was a change in hosting setup recently?
